# Generated by Django 5.2.1 on 2025-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_job_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter_file',
            field=models.FileField(default='default.pdf', upload_to='cover_letters/'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='aiscape', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='remote', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_package',
            field=models.CharField(default='5LPA', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(default='excel'),
        ),
    ]
